name: flutter_unionad
description: A flutter plugin for ad.
version: 2.0.9
homepage: https://github.com/gstory0404/flutter_unionad

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.gstory.flutter_unionad
        pluginClass: FlutterUnionadPlugin
      ios:
        pluginClass: FlutterUnionadPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
